@echo off
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Changing to SIH directory...
cd /d sih
echo Running SIH training...
call train.bat
echo Returning to root directory...
cd /d ..
echo Training finished.
pause
