@echo off
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Changing to SIH training directory...
cd /d src\sih
echo Running SIH training...
call train.bat
echo Returning to root directory...
cd /d ..
echo Training finished.
pause
