"""
AeroTwin Lightweight ML Pipeline
================================

The *simplest credible* ML pipeline for the digital twin: tree-based models
on engineered features (physics residuals + rolling statistics + sensor
correlations), trained and evaluated on the synthetic telemetry generated by
:mod:`simulator.telemetry_gen`.

Pipeline::

    physics_baseline ─► feature_engineering ─► labels ─► train ─► inference
    (expected values)   (residuals, rolling,    (class,    (RF/IF,  (streaming,
                         correlations, conds)     severity,  eval)    confidence,
                                                RUL)                 explainability)

Models (all CPU, all scikit-learn):
  * Anomaly detection   — Isolation Forest on healthy-only windows.
  * Fault classification — Random Forest, 9 classes.
  * Degradation          — Random Forest regressor (severity 0..1).
  * RUL                  — Random Forest regressor (log-minutes to failure).

No deep learning: engineered features already encode the trends/correlations
an LSTM would have to learn from raw series, with far less data and no GPU.

Modules
-------
physics_baseline.py    : analytic expected values → physics residuals.
feature_engineering.py : streaming window feature extractor.
labels.py              : class / severity / RUL labels + leakage-free run split.
training_data.py       : labelled run generation via simulator.telemetry_gen.
train.py               : CLI — generate → train → evaluate → serialize.
evaluate.py            : metrics, latency, confusion matrix, report.
inference.py           : CLI — stream a CSV through the trained bundle.
"""

__version__ = "0.1.0"